# Generated by Django 4.2.4 on 2023-08-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('no_of_travellers', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('image', models.FileField(max_length=500, null=True, upload_to='all_packages/')),
            ],
        ),
    ]
