# Generated by Django 4.2.4 on 2023-08-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combineddata',
            name='image',
            field=models.ImageField(null=True, upload_to='payments/'),
        ),
    ]
