# Generated by Django 4.2.4 on 2023-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_delete_status_combineddata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combineddata',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('not verified', 'Not Verified')], max_length=20, null=True),
        ),
    ]
