# Generated by Django 4.2.4 on 2023-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_combineddata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineddata',
            name='datetime_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
