# Generated by Django 4.2.4 on 2023-08-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_combineddata_datetime_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combineddata',
            name='datetime_field',
        ),
    ]
