# Generated by Django 4.2.4 on 2023-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_combineddata_datetime_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineddata',
            name='cnic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
