# Generated by Django 4.2.4 on 2023-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_combineddata_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineddata',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
