# Generated by Django 4.2.4 on 2023-08-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_combineddata_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combineddata',
            name='date_time',
        ),
    ]
