# Generated by Django 4.2.4 on 2023-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_combineddata_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineddata',
            name='package_names_string',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
