# Generated by Django 4.2.4 on 2023-08-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_combineddata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combineddata',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('not verified', 'Not Verified')], default='not verified', max_length=20),
        ),
    ]
