# Generated by Django 4.2.4 on 2023-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_combineddata_package_price_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineddata',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
