# Generated by Django 4.2.3 on 2023-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_packages_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_package',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
