# Generated by Django 4.2.3 on 2023-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_packages_section', '0002_alter_all_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_package',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
