# Generated by Django 4.2.3 on 2023-07-30 21:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('all_packages_section', '0003_all_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_package',
            name='details',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
