# Generated by Django 4.2.4 on 2023-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_packages_section', '0004_all_package_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_package',
            name='package_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
