# Generated by Django 4.2.3 on 2023-07-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photos',
            new_name='fixed_Photo',
        ),
    ]
