# Generated by Django 4.2.3 on 2023-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='special_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_package_name', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(max_length=500, null=True, upload_to='special_packages/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('days_nights', models.CharField(max_length=100)),
                ('max_people', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('reviews', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
