# Generated by Django 4.2.3 on 2023-07-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_packages_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_package',
            old_name='special_package_name',
            new_name='package_name',
        ),
    ]
