# Generated by Django 4.2.3 on 2023-07-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_logo',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
