# Generated by Django 4.2.3 on 2023-07-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_section', '0004_footer_gmail_footer_location_footer_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=50, null=True)),
                ('developer_link', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
