# Generated by Django 4.2.3 on 2023-07-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_section', '0005_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
