# Generated by Django 4.2.3 on 2023-07-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_number', models.CharField(max_length=50, null=True)),
                ('facebook_link', models.CharField(max_length=50)),
                ('instagram_link', models.CharField(max_length=50)),
                ('youtube_link', models.CharField(max_length=50)),
                ('header_heading', models.CharField(max_length=50)),
                ('header_paragraph', models.CharField(max_length=50)),
                ('header_logo', models.FileField(max_length=500, upload_to='header/')),
            ],
        ),
    ]
