# Generated by Django 4.2.3 on 2023-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='header_paragraph',
            field=models.TextField(max_length=50),
        ),
    ]
