# Generated by Django 4.2.3 on 2023-07-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_section', '0003_facebook_link_header_heading_header_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_logo',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
