# Generated by Django 4.2.3 on 2023-07-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_section', '0004_header_logo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_paragraph',
            name='header_paragraph',
            field=models.TextField(max_length=500),
        ),
    ]
