# Generated by Django 4.2.3 on 2023-07-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_section', '0005_alter_header_paragraph_header_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_link',
            name='facebook_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='header_heading',
            name='header_heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instagram_link',
            name='instagram_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youtube_link',
            name='youtube_link',
            field=models.CharField(max_length=200),
        ),
    ]
