# Generated by Django 4.2.3 on 2023-07-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_booking_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_data',
            old_name='phone',
            new_name='number',
        ),
    ]
