# Generated by Django 4.2.3 on 2023-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_booking_section', '0002_rename_phone_booking_data_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_data',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
