# Generated by Django 4.2.3 on 2023-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_booking_section', '0004_departure_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_city', models.CharField(max_length=100)),
            ],
        ),
    ]
