# Generated by Django 4.2.3 on 2023-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='description',
            field=models.TextField(max_length=130),
        ),
    ]
