# Generated by Django 4.2.3 on 2023-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_section', '0002_alter_team_members_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
