# Generated by Django 4.2.3 on 2023-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_section', '0004_remove_team_members_description_team_members_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
